service: content-moderation

provider:
    name: aws
    runtime: go1.x
    stage: ${opt:stage, "dev"}
    region: ${opt:region, "eu-central-1"}
    environment:
        GIN_MODE: release
        LOG_LEVEL: ${self:custom.stages.${opt:stage}.logging.level}
        ACCOUNT_ID: ${opt:account, "464378881349"}
        STAGE: ${opt:stage, "dev"}
        REGION: ${opt:region, "eu-central-1"}
        SQS_API_VERSION: ${opt:sqsApiVersion, "2012-11-05"}
        DDB_API_VERSION: ${opt:ddbApiVersion, "2012-08-10"}
        ILERT_HOST: https://api.${opt:domain, "ilert.dev"}
        ILERT_API_TOKEN: ${ssm:/monolith/LAMBDA_ACCESS_KEY~true}
        NOTIFICATION_ENABLED: "true"
        NOTIFICATION_ALARM_TOPIC_ARN: ${ssm:sns-ilert-functions-alerts-arn}
        GOOGLE_PROJECT_ID: ilert-${opt:stage}
        GOOGLE_LOCATION: EU
        LOKI_ENABLED: "true"
        LOKI_QUEUE_ENABLED: "true"
        LOKI_LOGS_TOPIC_ARN: ${ssm:sns-ilert-logs-arn}
      tracing:
        apiGateway: false
        lambda: false
      logRetentionInDays: ${self:custom.stages.${opt:stage}.logging.retentionInDays}
      endpointType: REGIONAL
      iam:
        role:
          statements:
            - Effect: Allow
              Action: sns:Publish
              Resource: ${ssm:sns-ilert-functions-alerts-arn}
            - Effect: Allow
              Action: sns:Publish
              Resource: ${ssm:sns-ilert-logs-arn}
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: ${ssm:sqs-ilert-incidents-arn}
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: ${ssm:sqs-ilert-incidents-fifo-arn}
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: ${ssm:sqs-ilert-webhook-retries-fifo-arn}
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: ${ssm:sqs-ilert-auto-webhook-logs-arn}
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:DeleteItem
              Resource: ${ssm:ddb-ilert-webhooks-arn}
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: ${ssm:ddb-ilert-extensions-arn}
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: ${ssm:ddb-ilert-incident-references-arn}
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: ${ssm:ddb-ilert-incident-references-arn}/index/${ssm:ddb-ilert-incident-references-incident-index-index}
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: ${ssm:ddb-ilert-incident-references-arn}/index/${ssm:ddb-ilert-incident-references-incident-id-index}
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: ${ssm:ddb-ilert-webhooks-arn}/index/${ssm:ddb-ilert-webhooks-tenant-index}
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: ${ssm:ddb-ilert-webhooks-arn}/index/${ssm:ddb-ilert-webhooks-alert-source-index}
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: ${ssm:ddb-ilert-extensions-arn}/index/${ssm:ddb-ilert-extensions-index}
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: ${ssm:ddb-ilert-extensions-arn}/index/${ssm:ddb-ilert-extensions-workspace-index}
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: ${ssm:ddb-ilert-slack-bots-arn}
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: ${ssm:ddb-ilert-slack-bots-arn}/index/${ssm:ddb-ilert-slack-bots-index}
            - Effect: Allow
              Action:
                - s3:*
              Resource:
                - arn:aws:s3:::${ssm:bigquery-ilert-webhooks-service-account-bucket-name}
                - arn:aws:s3:::${ssm:bigquery-ilert-webhooks-service-account-bucket-name}/*
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource:
                - "*"
            - Effect: Allow
              Action:
                - events:PutPartnerEvents
              Resource:
                - "*"
            - Effect: Allow
              Action: sns:Publish
              Resource: ${ssm:sns-ilert-lambda-entity-operations-fifo-arn}

functions:
    consumer:
        handler: bin/consume
        events:
            - sqs:
                  arn: ${ssm:sqs-content-moderation-arn}
                  batchSize: 10
